env:
  browser: true
  es2021: true
  'jest/globals': true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - jest
  - react
  - '@typescript-eslint'
rules: {
  'no-use-before-define': 'off',
  '@typescript-eslint/no-use-before-define': 'error',
  'react/react-in-jsx-scope': 'off',
}
settings:
  react:
    version: detect
